id: medcom.fhir.dk.acknowledgement
canonical: http://medcomfhir.dk/ig/acknowledgement
name: MedComAcknowledgement
title: "DK MedCom acknowledgement"
description: The DK MedCom acknowledgement IG
status: active
version: "2.0.0"
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: Build CI
publisher:
  name: MedCom
  url: http://www.medcom.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
dependencies:
  hl7.fhir.dk.core:
   uri: https://hl7.dk/fhir/core/2.0.0/
   version: 2.0.0
  medcom.fhir.dk.core: current
  medcom.fhir.dk.messaging: current


menu:
  Table of Contents: toc.html
  Home: index.html
  Profiles: profiles.html
  Extensions: extensions.html
  Artifacts: artifacts.html
  Downloads: downloads.html

parameters:
  apply-contact: true
  apply-juristiction: true
  apply-publisher: true
