title: "MedCom STANDARDNAME in FHIR"
description: "This page includes content about STANDARDNAME (DA: STANDARDNAVN)"
logo: /assets/Images/MedCom+HL7 FHIR_4.png
description: "MedCom standard based on HL7 FHIR"
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
version: "Version 2.0.3"
fhir_version: "FHIR®© R4"
releasenote: https://github.com/medcomdk/dk-medcom-acknowledgement/releases
thisurl: https://medcomdk.github.io/dk-medcom-acknowledgement/
menuurl_item1: https://medcomdk.github.io/MedComLandingPage/
menutxt_item1: MedCom FHIR®© LandingPage